title: HTTPS Plugin Confiugration
type: object
properties:
  servers:
    title: WS Servers
    type: object
    additionalProperties:
      title: HTTPS Server Configuration
      type: object
      properties:
        httpServer:
          title: HTTP Server
          type: string
    nullable: true
additionalProperties: false