kafka:
  connections:
    default:
      clientId: "{{SERVICE_NAME}}"
      ssl: true
      brokers:
        - "{{KAFKA_BROKER}}"
      sasl:
        mechanism: plain
        username: "{{KAFKA_USERNAME}}"
        password: "{{KAFKA_PASSWORD}}"
