title: MongoDb Plugin Configuration
type: object
properties:
  connections:
    title: Connections
    type: object
    nullable: true
    patternProperties:
      "[a-z][a-zA-Z0-9]*":
        type: object
        properties:
          connectionString:
            title: Connection String
            type: string
          useNewUrlParser:
            title: Use New Url Parser
            type: boolean
            default: true
          useUnifiedTopology:
            title: Use Unified Topology
            type: boolean
            default: true
          collections:
            title: Collections
            type: object
            additionalProperties:
              type: object
              properties:
                validator:
                  title: Validator
                  type: object
                  properties:
                    $jsonSchema:
                      title: JSON Schema
                      type: object
                  additionalProperties: false
                validationLevel:
                  title: Validation Level
                  type: string
                  enum:
                    - off
                    - moderate
                    - strict
                  default: strict
                validationAction:
                  title: Validation Action
                  type: string
                  enum:
                    - error
                    - warn
                  default: error
                indexes:
                  title: Indexes
                  type: array
                  items:
                    type: array
                    items:
                      - title: Index Specification
                        type: object
                        additionalProperties:
                          type:
                            - integer
                            - string
                      - title: Index Options
                        type: object
                        properties:
                          sparse:
                            description:
                              Sparse indexes only contain entries for documents that have the
                              indexed field, even if the index field contains a
                              null value
                            type: boolean
                          unique:
                            description: A unique index ensures that the indexed fields do not store
                              duplicate values; i.e. enforces uniqueness for the
                              indexed fields.
                            type: boolean
                          partialFilterExpression:
                            type: object
                            additionalProperties: true
                          expireAfterSeconds:
                            description: Expire Documents after a Specified Number of Seconds
                            type: integer
                        additionalProperties: false
                    additionalItems: false
                    minItems: 1
                  minItems: 0
              additionalProperties: false
        additionalProperties: false
    required:
      - default
additionalProperties: false
