title: Express Plugin Configuration
type: object
properties:
  apps:
    title: Apps
    type: object
    additionalProperties:
      title: App Config
      type: object
      properties:
        servers:
          title: HTTP(S) Servers
          type: array
          items:
            title: HTTP(S) Server ID
            type: string
    nullable: true
