title: Express Plugin Configuration
type: object
nullable: true
properties:
  apps:
    title: Apps
    type: object
    additionalProperties:
      title: App Config
      type: object
      properties:
        server:
          title: Server
          type: string
