type: object
nullable: true
properties:
  plugins:
    type: object
    properties:
      express:
        title: Express Plugin Configuration
        type: object
        nullable: true
        properties:
          apps:
            title: Apps
            type: object
            additionalProperties:
              $ref: '#/definitions/ExpressAppConfig'
definitions:
  ExpressAppConfig:
    title: App Config
    type: object
    properties:
      server:
        title: Server
        type: string
