title: AMQP Plugin Configuration
type: object
properties:
  connections:
    title: Connections
    type: object
    patternProperties:
      "[a-z][a-zA-Z0-9]*":
        type: object
        properties:
          connectionString:
            title: Connection String
            description: ""
            type: string
        additionalProperties: false
    required:
      - default
    nullable: true
additionalProperties: false
