title: HTTP Plugin Confiugration
type: object
properties:
  servers:
    title: HTTP Servers
    type: object
    additionalProperties:
      title: HTTP Server Configuration
      type: object
      properties:
        port:
          title: Port
          type: number
          default: 8078
    nullable: true
additionalProperties: false