title: HTTP Plugin Confiugration
type: object
nullable: true
properties:
  servers:
    title: Servers
    type: object
    additionalProperties:
      title: Server Configuration
      type: object
      properties:
        port:
          title: Port
          type: number
          default: 7877
        maxHeadersCount:
          title: Max Headers Count
          type: number
        requestTimeout:
          title: Request Timeout
          type: number
        timeout:
          title: Timeout
          type: number
        keepAliveTimeout:
          title: Keep Alive Timeout
          type: number
